<robot name="four_wheeled_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.14159265359" />

    <!-- Parameters -->
    <xacro:property name="chassis_length" value="0.5" /> <!-- 50 cm -->
    <xacro:property name="chassis_width" value="0.4" />  <!-- 40 cm -->
    <xacro:property name="chassis_height" value="0.1" /> <!-- 10 cm -->

    <xacro:property name="wheel_diameter" value="0.152" /> <!-- 15.2 cm -->
    <xacro:property name="wheel_radius" value="${wheel_diameter / 2}" />
    <xacro:property name="wheel_width" value="0.02" /> <!-- 2 cm -->

    <xacro:property name="telescopic_rod_min_length" value="0.1" /> <!-- 10 cm -->
    <xacro:property name="telescopic_rod_max_length" value="0.3" /> <!-- 30 cm -->
    <xacro:property name="telescopic_rod_radius" value="0.02" /> <!-- 2 cm -->

    <xacro:property name="body_top_length" value="0.5" /> <!-- 30 cm -->
    <xacro:property name="body_top_width" value="0.4" />  <!-- 30 cm -->
    <xacro:property name="body_top_height" value="0.2" /> <!-- 20 cm -->

    <!-- Base Link -->
    <link name="base_link">
        <visual>
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
            <material name="gray" />
        </visual>
        <collision>
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="10.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
        </inertial>
    </link>

    <!-- Four Wheels -->
    <link name="wheel_fl">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <link name="wheel_fr">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <link name="wheel_bl">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <link name="wheel_br">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <!-- Joints for Wheels -->
    <joint name="joint_wheel_fl" type="continuous">
        <parent link="base_link" />
        <child link="wheel_fl" />
        <origin xyz="${-chassis_width/2} ${chassis_length/2-wheel_radius} -${chassis_height/2}"
            rpy="0 ${-PI/2} 0" /> <!--
        Place wheel at the front-left corner -->
        <axis xyz="0 0 1" />
    </joint>

    <joint name="joint_wheel_fr" type="continuous">
        <parent link="base_link" />
        <child link="wheel_fr" />
        <origin xyz="${chassis_width/2} ${chassis_length/2-wheel_radius} -${chassis_height/2}"
            rpy="0 ${-PI/2} 0" /> <!--
        Place wheel at the front-right corner -->
        <axis xyz="0 0 1" />
    </joint>

    <joint name="joint_wheel_bl" type="continuous">
        <parent link="base_link" />
        <child link="wheel_bl" />
        <origin xyz="${-chassis_width/2} -${chassis_length/2-wheel_radius} -${chassis_height/2}"
            rpy="0 ${-PI/2} 0" /> <!--
        Place wheel at the back-left corner -->
        <axis xyz="0 0 1" />
    </joint>

    <joint name="joint_wheel_br" type="continuous">
        <parent link="base_link" />
        <child link="wheel_br" />
        <origin xyz="${chassis_width/2} -${chassis_length/2-wheel_radius} -${chassis_height/2}"
            rpy="0 ${-PI/2} 0" /> <!-- Place wheel at the back-right corner -->
        <axis xyz="0 0 1" />
    </joint>

    <!-- Telescopic Rod -->
    <link name="telescopic_rod">
        <visual>
            <geometry>
                <cylinder radius="${telescopic_rod_radius}" length="${telescopic_rod_max_length}" />
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${telescopic_rod_radius}" length="${telescopic_rod_max_length}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>
    </link>

    <!-- Joint for Telescopic Rod -->
    <joint name="joint_telescopic_rod" type="fixed">
        <parent link="base_link" />
        <child link="telescopic_rod" />
        <origin xyz="0 0 ${(chassis_height+telescopic_rod_max_length)/2}" /> <!-- Attach rod to the top of the base -->
    </joint>

    <!-- Body Link on Top of Telescopic Rod -->
    <link name="body_top">
        <visual>
            <geometry>
                <box size="${body_top_width} ${body_top_length} ${body_top_height}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${body_top_width} ${body_top_length} ${body_top_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="2.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02" />
        </inertial>
    </link>

    <!-- Joint for Body Top -->
    <joint name="joint_body_top" type="prismatic">
        <parent link="telescopic_rod" />
        <child link="body_top" />
        <origin
            xyz="0 0 ${(telescopic_rod_max_length + body_top_height) / 2-(telescopic_rod_max_length-telescopic_rod_min_length)}" /> <!-- Attach body to
        the top of the rod -->
        <axis xyz="0 0 1" />
        <limit lower="0" upper="${telescopic_rod_max_length-telescopic_rod_min_length}"
            effort="10.0" velocity="0.05" /> <!-- 10 cm to 30 cm -->
    </joint>

    <!-- Transmission for the wheels -->
    <transmission name="trans_wheel_fl">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_fl">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="actuator_wheel_fl">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_wheel_fr">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_fr">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="actuator_wheel_fr">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_wheel_bl">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_bl">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="actuator_wheel_bl">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_wheel_br">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_br">
            <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="actuator_wheel_br">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Gazebo plugin for differential drive control -->
    <gazebo>
        <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <namespace>/my_robot</namespace>
                <remapping>cmd_vel:=cmd_vel</remapping>
            </ros>
            <updateRate>50</updateRate>
            <leftJoint>joint_wheel_bl</leftJoint>
            <leftJoint>joint_wheel_fl</leftJoint>
            <rightJoint>joint_wheel_br</rightJoint>
            <rightJoint>joint_wheel_fr</rightJoint>
            <wheelSeparation>${chassis_width}</wheelSeparation>
            <wheelDiameter>${wheel_diameter}</wheelDiameter>
            <torque>0.5</torque>
        </plugin>
    </gazebo>
</robot>