<robot name="robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="PI" value="3.14159265359" />
    <xacro:property name="namespace" value="robot" />

    <!-- Parameters -->
    <xacro:property name="chassis_length" value="0.1" /> <!-- 50 cm -->
    <xacro:property name="chassis_width" value="0.4" />  <!-- 40 cm -->
    <xacro:property name="chassis_height" value="0.01" /> <!-- 1 cm -->

    <xacro:property name="wheel_diameter" value="0.152" /> <!-- 15.2 cm -->
    <xacro:property name="wheel_radius" value="${wheel_diameter / 2}" />
    <xacro:property name="wheel_width" value="0.02" /> <!-- 2 cm -->

    <xacro:property name="caster_radius" value="0.03" /> <!-- 15.2 cm -->

    <xacro:property name="min_lift_height" value="0.1" /> <!-- 10 cm -->
    <xacro:property name="max_lift_height" value="0.3" /> <!-- 30 cm -->
    <!-- <xacro:property name="telescopic_rod_radius" value="0.03" /> -->

    <xacro:property name="body_top_length" value="0.4" /> <!-- 30 cm -->
    <xacro:property name="body_top_width" value="0.4" />  <!-- 30 cm -->
    <xacro:property name="body_top_height" value="0.2" /> <!-- 20 cm -->

    <!-- Base Link -->
    <link name="base_link">
        <!-- <visual>
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
            <material name="gray" />
        </visual> -->
        <!-- <collision>
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
        </collision> -->
        <inertial>
            <mass value="10.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
        </inertial>
    </link>

    <!-- Four Wheels -->
    <link name="wheel_left">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <link name="wheel_right">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01" />
        </inertial>
    </link>

    <!-- Joints for Wheels -->
    <joint name="joint_wheel_left" type="continuous">
        <parent link="base_link" />
        <child link="wheel_left" />
        <origin xyz="${-chassis_width/2} 0 -${chassis_height/2}"
            rpy="0 ${-PI/2} 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="joint_wheel_right" type="continuous">
        <parent link="base_link" />
        <child link="wheel_right" />
        <origin xyz="${chassis_width/2} 0 -${chassis_height/2}"
            rpy="0 ${-PI/2} 0" />
        <axis xyz="0 0 1" />
    </joint>

    <link name="caster_forward">
        <!-- <visual>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual> -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
        </collision>
        <!-- <inertial>
            <mass value="0.5" />
            <inertia ixx="3.000e-4" iyy="3.000e-4" izz="3.000e-4" ixy="0" ixz="0" iyz="0" />
        </inertial> -->
    </link>

    <link name="caster_backward">
        <!-- <visual>
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green" />
        </visual> -->
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0" />
            <geometry>
                <sphere radius="${caster_radius}" />
            </geometry>
        </collision>
        <!-- <inertial>
            <mass value="0.5" />
            <inertia ixx="3.000e-4" iyy="3.000e-4" izz="3.000e-4" ixy="0" ixz="0" iyz="0" />
        </inertial> -->
    </link>

    <joint name="caster_forward_joint" type="fixed">
        <origin
            xyz="0 ${body_top_length/2-caster_radius} ${-chassis_height/2-wheel_radius+caster_radius}"
            rpy="0 0 0" />
        <parent link="base_link" />
        <child link="caster_forward" />
    </joint>

    <joint name="caster_backward_joint" type="fixed">
        <origin
            xyz="0 ${-body_top_length/2+caster_radius} ${-chassis_height/2-wheel_radius+caster_radius}"
            rpy="0 0 0" />
        <parent link="base_link" />
        <child link="caster_backward" />
    </joint>

    <!-- Telescopic Rod -->
    <!-- <link name="telescopic_rod">
        <visual>
            <geometry>
                <cylinder radius="${telescopic_rod_radius}" length="${max_lift_height}" />
            </geometry>
            <material name="silver" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${telescopic_rod_radius}" length="${max_lift_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.5" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>
    </link> -->

    <!-- Joint for Telescopic Rod -->
    <!-- <joint name="joint_telescopic_rod" type="fixed">
        <parent link="base_link" />
        <child link="telescopic_rod" />
        <origin xyz="0 0 ${(chassis_height+max_lift_height)/2}" />
    </joint> -->

    <!-- Body Link on Top of Telescopic Rod -->
    <link name="body_top">
        <visual>
            <geometry>
                <box size="${body_top_width} ${body_top_length} ${body_top_height}" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${body_top_width} ${body_top_length} ${body_top_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="2.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.02" ixy="0.0" ixz="0.0" iyy="0.02" iyz="0.0" izz="0.02" />
        </inertial>
    </link>

    <!-- Joint for Body Top -->
    <xacro:property name="lift_origin"
        value="${body_top_height / 2}" />
    <joint name="joint_body_top" type="prismatic">
        <parent link="base_link" />
        <child link="body_top" />
        <origin
            xyz="0 0 ${lift_origin}" />
        <axis xyz="0 0 1" />
        <limit lower="${min_lift_height}" upper="${max_lift_height}"
            effort="10.0" velocity="0.05" /> <!-- 10 cm to 30 cm -->
    </joint>

    <link name="body_top_semantic">
        <visual>
            <geometry>
                <sphere radius="${body_top_width/8}" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${body_top_width/8}" />
            </geometry>
        </collision>
    </link>

    <joint name="joint_body_top_semantic" type="fixed">
        <parent link="body_top" />
        <child link="body_top_semantic" />
        <origin
            xyz="0 ${body_top_length/2-body_top_width/8} ${body_top_height/2}" />
    </joint>

    <!-- Transmission for the wheels -->
    <transmission name="trans_wheel_left">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_left">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="actuator_wheel_left">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_wheel_right">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_wheel_right">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
        </joint>
        <actuator name="actuator_wheel_right">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans_body_top">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="joint_body_top">
            <hardwareInterface>PositionJointInterface</hardwareInterface>
        </joint>
        <actuator name="actuator_body_top">
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <!-- Gazebo plugin for differential drive control -->
    <gazebo>
        <plugin name="gazebo_ros_diff_drive" filename="libgazebo_ros_diff_drive.so">
            <ros>
                <namespace>/${namespace}</namespace>
                <remapping>cmd_vel:=cmd_vel</remapping>
            </ros>
            <updateRate>50</updateRate>
            <leftJoint>joint_wheel_left</leftJoint>
            <rightJoint>joint_wheel_right</rightJoint>
            <wheelSeparation>${chassis_width}</wheelSeparation>
            <wheelDiameter>${wheel_diameter}</wheelDiameter>
            <torque>5</torque>
        </plugin>
    </gazebo>

    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo reference="wheel_left">
        <material>Gazebo/DarkGrey</material>
    </gazebo>
    <gazebo reference="wheel_right">
        <material>Gazebo/DarkGrey</material>
    </gazebo>
    <gazebo reference="telescopic_rod">
        <material>Gazebo/White</material>
    </gazebo>
    <gazebo reference="body_top">
        <material>Gazebo/DarkYellow </material>
    </gazebo>
    <gazebo reference="body_top_semantic">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <gazebo reference="caster_forward">
        <mu1 value="0.0" />
        <mu2 value="0.0" />
    </gazebo>
    <gazebo reference="caster_backward">
        <mu1 value="0.0" />
        <mu2 value="0.0" />
    </gazebo>
</robot>