<?xml version="1.0" encoding="utf-8"?>
<!-- This URDF was automatically created by SolidWorks to URDF Exporter! Originally created by
Stephen Brawner (brawner@gmail.com) 
     Commit Version: 1.6.0-1-g15f4949  Build Version: 1.6.7594.29634
     For more information, please see http://wiki.ros.org/sw_urdf_exporter -->
<robot
  xmlns:xacro="http://www.ros.org/wiki/xacro"
  name="sw">
  <xacro:property name="PI" value="3.14159265359" />
  <xacro:arg name="ns" default="robot" />

  <!-- Parameters -->
  <xacro:property name="chassis_length" value="0.1" />
  <xacro:property name="chassis_width" value="0.45" />
  <xacro:property name="chassis_height" value="0.01" />

  <xacro:property name="wheel_diameter" value="0.152" />
  <xacro:property name="wheel_radius" value="${wheel_diameter / 2}" />
  <xacro:property name="wheel_width" value="0.046" />

  <xacro:property name="caster_radius" value="0.03" />

  <xacro:property name="min_lift_height" value="0.012" />
  <xacro:property name="max_lift_height" value="0.305" />

  <xacro:property name="body_top_length" value="0.440" />
  <xacro:property name="body_top_width" value="0.309" />
  <xacro:property name="body_top_height" value="0.140" />
  <link
    name="base_link">
    <!-- <inertial>
      <origin
        xyz="-0.0101783300438887 -8.63948981799645E-09 0.0390008530568618"
        rpy="0 0 0" />
      <mass
        value="6.78677551342344" />
      <inertia
        ixx="0.0710000990521389"
        ixy="3.51370404321391E-09"
        ixz="0.000957296781231614"
        iyy="0.0868439733337961"
        iyz="1.26514888593879E-10"
        izz="0.142687618659048" />
    </inertial> -->
    <inertial>
      <origin
        xyz="-0.0101783300438887 -8.63948981799645E-09 0.0390008530568618"
        rpy="0 0 0" />
      <mass
        value="0.678677551342344" />
      <inertia
        ixx="0.0710000990521389"
        ixy="3.51370404321391E-09"
        ixz="0.000957296781231614"
        iyy="0.0868439733337961"
        iyz="1.26514888593879E-10"
        izz="0.000142687618659048" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/base_link.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_top_length} ${body_top_width} ${body_top_height}" />
      </geometry>
    </collision>
  </link>
  <link
    name="link_thigh_lf">
    <inertial>
      <origin
        xyz="0.0569002619592844 0.022256442328326 -3.46944695195361E-18"
        rpy="0 0 0" />
      <mass
        value="0.000162466897479642" />
      <inertia
        ixx="3.86909457658897E-05"
        ixy="-3.14607317451276E-05"
        ixz="9.67875140257797E-21"
        iyy="0.000516860098106676"
        iyz="-4.99172496310924E-22"
        izz="0.000499248643219268" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_lf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_lf.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_thigh_lf"
    type="revolute">
    <origin
      xyz="0.040664 0.1545 0.057"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_thigh_lf" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="12"
      velocity="0" />
  </joint>
  <link
    name="link_leg_lf">
    <inertial>
      <origin
        xyz="-0.142293835284382 0.0154549695933409 -0.103443136570321"
        rpy="0 0 0" />
      <mass
        value="0.000347077595551188" />
      <inertia
        ixx="0.00107716081650825"
        ixy="0.000121336045655202"
        ixz="-0.00129257437958523"
        iyy="0.00291267231792872"
        iyz="8.82074835956815E-05"
        izz="0.0019155334891395" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_lf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_lf.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_leg_lf"
    type="revolute">
    <origin
      xyz="0.141 0.033 0"
      rpy="0 0 0" />
    <parent
      link="link_thigh_lf" />
    <child
      link="link_leg_lf" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="link_wheel_l">
    <inertial>
      <origin
        xyz="1.38777878078145E-17 0.00549999999999989 -1.38777878078145E-17"
        rpy="0 0 0" />
      <mass
        value="0.601239032775837" />
      <inertia
        ixx="0.00119873850622409"
        ixy="-1.52360615762972E-21"
        ixz="-2.16840434497101E-19"
        iyy="0.0021958696896456"
        iyz="-4.32365595013048E-21"
        izz="0.00119873850622409" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_wheel_l.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_wheel_l.STL" />
      </geometry>
    </collision>
  </link>
  <!-- <joint
    name="joint_wheel_l"
    type="continuous">
    <origin
      xyz="-0.201 0.042 -0.14612"
      rpy="3.1416 0.6286 3.1416" />
    <parent
      link="link_leg_lf" />
    <child
      link="link_wheel_l" />
    <axis
      xyz="0 1 0" />
  </joint> -->
  <link
    name="link_thigh_lb">
    <inertial>
      <origin
        xyz="-0.0711683948181995 0.00758058660928651 1.21430643318376E-17"
        rpy="0 0 0" />
      <mass
        value="0.000129894864847223" />
      <inertia
        ixx="2.59618087625984E-05"
        ixy="7.30982349481323E-07"
        ixz="5.23943156609902E-20"
        iyy="0.000375578896519083"
        iyz="-1.46504672935141E-22"
        izz="0.000354619050026521" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_lb.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_lb.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_thigh_lb"
    type="revolute">
    <origin
      xyz="-0.079336 0.1545 0.057"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_thigh_lb" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="12"
      velocity="0" />
  </joint>
  <link
    name="link_leg_lb">
    <inertial>
      <origin
        xyz="0.115661076605591 0.00982868621876615 -0.0840819598352317"
        rpy="0 0 0" />
      <mass
        value="0.00024006664343355" />
      <inertia
        ixx="0.000709486550862449"
        ixy="-6.73380406076644E-06"
        ixz="0.00089318704529918"
        iyy="0.00198824506961512"
        iyz="4.8952634645311E-06"
        izz="0.00128881383922118" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_lb.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_lb.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_leg_lb"
    type="revolute">
    <origin
      xyz="-0.141 0.015 0"
      rpy="0 0 0" />
    <parent
      link="link_thigh_lb" />
    <child
      link="link_leg_lb" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="link_driven_lf">
    <inertial>
      <origin
        xyz="0 0.000988036020187399 0"
        rpy="0 0 0" />
      <mass
        value="0.00026831378984772" />
      <inertia
        ixx="4.30409377850185E-06"
        ixy="3.76310597444988E-23"
        ixz="-8.65900863948802E-40"
        iyy="7.60093161576196E-06"
        iyz="7.95992041548934E-39"
        izz="4.30409377850185E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_lf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_lf.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_driven_lf"
    type="continuous">
    <origin
      xyz="0.064364 0.124 -0.0741"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_driven_lf" />
    <axis
      xyz="0 -1 0" />
  </joint>
  <link
    name="link_driven_lb">
    <inertial>
      <origin
        xyz="0 0.000988036020187399 0"
        rpy="0 0 0" />
      <mass
        value="0.00026831378984772" />
      <inertia
        ixx="4.30409377850185E-06"
        ixy="3.76310597444988E-23"
        ixz="-8.65900863948802E-40"
        iyy="7.60093161576196E-06"
        iyz="7.95992041548934E-39"
        izz="4.30409377850185E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_lb.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_lb.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_driven_lb"
    type="continuous">
    <origin
      xyz="-0.10304 0.124 -0.0741"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_driven_lb" />
    <axis
      xyz="0 -1 0" />
  </joint>
  <link
    name="link_thigh_rf">
    <inertial>
      <origin
        xyz="0.0569002619592844 -0.0222564423283261 8.67361737988404E-18"
        rpy="0 0 0" />
      <mass
        value="0.000162466897479642" />
      <inertia
        ixx="3.86909457658898E-05"
        ixy="3.14607317451277E-05"
        ixz="-1.00436854088154E-19"
        iyy="0.000516860098106676"
        iyz="-4.02211304567183E-21"
        izz="0.000499248643219269" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_rf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_rf.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_thigh_rf"
    type="revolute">
    <origin
      xyz="0.040664 -0.1545 0.057"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_thigh_rf" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="12"
      velocity="0" />
  </joint>
  <link
    name="link_leg_rf">
    <inertial>
      <origin
        xyz="-0.142293835284383 -0.0154549695933407 -0.103443136570321"
        rpy="0 0 0" />
      <mass
        value="0.000347077595551188" />
      <inertia
        ixx="0.00107716081650825"
        ixy="-0.000121336045655203"
        ixz="-0.00129257437958523"
        iyy="0.00291267231792872"
        iyz="-8.82074835956817E-05"
        izz="0.0019155334891395" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_rf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_rf.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_leg_rf"
    type="revolute">
    <origin
      xyz="0.141 -0.033 0"
      rpy="0 0 0" />
    <parent
      link="link_thigh_rf" />
    <child
      link="link_leg_rf" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="link_wheel_r">
    <inertial>
      <origin
        xyz="-4.16333634234434E-17 -0.00550000000000002 2.77555756156289E-17"
        rpy="0 0 0" />
      <mass
        value="0.601239032775837" />
      <inertia
        ixx="0.00119873850622409"
        ixy="-1.43412681656239E-20"
        ixz="5.42101086242752E-20"
        iyy="0.0021958696896456"
        iyz="1.63745329402191E-20"
        izz="0.00119873850622409" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_wheel_r.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_wheel_r.STL" />
      </geometry>
    </collision>
  </link>
  <!-- <joint
    name="joint_wheel_r"
    type="continuous">
    <origin
      xyz="-0.201 -0.042 -0.14612"
      rpy="-3.1416 0.6286 -3.1416" />
    <parent
      link="link_leg_rf" />
    <child
      link="link_wheel_r" />
    <axis
      xyz="0 -1 0" />
  </joint> -->
  <link
    name="link_thigh_rb">
    <inertial>
      <origin
        xyz="-0.0711683948181994 -0.00758058660928647 6.93889390390723E-18"
        rpy="0 0 0" />
      <mass
        value="0.000129894864847223" />
      <inertia
        ixx="2.59618087625984E-05"
        ixy="-7.30982349481324E-07"
        ixz="2.68045543044662E-20"
        iyy="0.000375578896519082"
        iyz="5.31288825051781E-22"
        izz="0.00035461905002652" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_rb.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_thigh_rb.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_thigh_rb"
    type="revolute">
    <origin
      xyz="-0.079336 -0.1545 0.057"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_thigh_rb" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="12"
      velocity="0" />
  </joint>
  <link
    name="link_leg_rb">
    <inertial>
      <origin
        xyz="-0.115661076605591 -0.00982868621876613 0.0840819598352318"
        rpy="0 0 0" />
      <mass
        value="0.000240066643433549" />
      <inertia
        ixx="0.000709486550862448"
        ixy="-6.73380406076642E-06"
        ixz="0.000893187045299179"
        iyy="0.00198824506961511"
        iyz="4.89526346453109E-06"
        izz="0.00128881383922118" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_rb.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_leg_rb.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_leg_rb"
    type="revolute">
    <origin
      xyz="-0.141 -0.015 0"
      rpy="3.1416 0 3.1416" />
    <parent
      link="link_thigh_rb" />
    <child
      link="link_leg_rb" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="0"
      velocity="0" />
  </joint>
  <link
    name="link_driven_rf">
    <inertial>
      <origin
        xyz="0 -0.009880360201874 0"
        rpy="0 0 0" />
      <mass
        value="0.000026831378984772" />
      <inertia
        ixx="4.30409377850185E-06"
        ixy="3.76310597444988E-23"
        ixz="8.65900863948803E-40"
        iyy="7.60093161576196E-06"
        iyz="-7.95992041548932E-39"
        izz="4.30409377850184E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_rf.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_rf.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_driven_rf"
    type="continuous">
    <origin
      xyz="0.064364 -0.124 -0.0741"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_driven_rf" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="link_driven_rb">
    <inertial>
      <origin
        xyz="1.38777878078145E-17 -0.009880360201874 0"
        rpy="0 0 0" />
      <mass
        value="0.000026831378984772" />
      <inertia
        ixx="4.30409377850185E-06"
        ixy="3.76310597444988E-23"
        ixz="8.65900863948803E-40"
        iyy="7.60093161576196E-06"
        iyz="-7.95992041548932E-39"
        izz="4.30409377850184E-06" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_rb.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_driven_rb.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_driven_rb"
    type="continuous">
    <origin
      xyz="-0.10304 -0.124 -0.0741"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_driven_rb" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="link_armbase_r">
    <inertial>
      <origin
        xyz="-5.55111512312578E-17 1.38777878078145E-17 0.0219798785203744"
        rpy="0 0 0" />
      <mass
        value="0.000141168695994094" />
      <inertia
        ixx="8.42336911882901E-05"
        ixy="4.92560402606528E-21"
        ixz="1.0562733032858E-21"
        iyy="4.54835087478442E-05"
        iyz="-1.41719711734731E-21"
        izz="8.41033788238504E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_armbase_r.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_armbase_r.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_armbase_r"
    type="revolute">
    <origin
      xyz="0.11116 -0.0555 0.067"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_armbase_r" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="0"
      upper="0"
      effort="6"
      velocity="0" />
  </joint>
  <link
    name="link_arm_r">
    <inertial>
      <origin
        xyz="-0.127740362351781 0.036245374218048 0.00213044981218816"
        rpy="0 0 0" />
      <mass
        value="0.000239903536199401" />
      <inertia
        ixx="7.70561826554075E-05"
        ixy="4.41905722774107E-08"
        ixz="-1.02697125646325E-05"
        iyy="0.0011697022299499"
        iyz="-9.98811107138354E-08"
        izz="0.00121279798416084" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_arm_r.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_arm_r.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_arm_r"
    type="revolute">
    <origin
      xyz="0 -0.03621 0.04006"
      rpy="3.1416 0 3.1416" />
    <parent
      link="link_armbase_r" />
    <child
      link="link_arm_r" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="6"
      velocity="0" />
  </joint>
  <link
    name="link_littlearm_r">
    <inertial>
      <origin
        xyz="0.128294239863031 0.0145 -1.38777878078145E-17"
        rpy="0 0 0" />
      <mass
        value="0.000157217277786466" />
      <inertia
        ixx="1.93415806521528E-05"
        ixy="6.58902012539697E-20"
        ixz="-2.50816941433529E-20"
        iyy="0.000877613801366261"
        iyz="-1.75005407101839E-23"
        izz="0.000880308842483845" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_littlearm_r.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_littlearm_r.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_littlearm_r"
    type="revolute">
    <origin
      xyz="-0.23682 0.02171 -0.03"
      rpy="0 0 0" />
    <parent
      link="link_arm_r" />
    <child
      link="link_littlearm_r" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="6"
      velocity="0" />
  </joint>
  <link
    name="link_armbase_l">
    <inertial>
      <origin
        xyz="-2.77555756156289E-17 0 0.0219798785203744"
        rpy="0 0 0" />
      <mass
        value="0.000141168695994094" />
      <inertia
        ixx="8.42336911882902E-05"
        ixy="4.24490717382806E-21"
        ixz="-1.26084811174834E-22"
        iyy="4.54835087478443E-05"
        iyz="-1.51957114362797E-21"
        izz="8.41033788238504E-05" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_armbase_l.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_armbase_l.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_armbase_l"
    type="revolute">
    <origin
      xyz="0.11116 0.0555 0.067"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="link_armbase_l" />
    <axis
      xyz="0 0 1" />
    <limit
      lower="0"
      upper="0"
      effort="6"
      velocity="0" />
  </joint>
  <link
    name="link_arm_l">
    <inertial>
      <origin
        xyz="-0.127740362351781 0.036245374218048 0.00213044981218816"
        rpy="0 0 0" />
      <mass
        value="0.000239903536199401" />
      <inertia
        ixx="7.70561826554075E-05"
        ixy="4.41905722776166E-08"
        ixz="-1.02697125646323E-05"
        iyy="0.00116970222994989"
        iyz="-9.98811107138473E-08"
        izz="0.00121279798416084" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_arm_l.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_arm_l.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_arm_l"
    type="revolute">
    <origin
      xyz="0 -0.03621 0.04006"
      rpy="3.1416 0 3.1416" />
    <parent
      link="link_armbase_l" />
    <child
      link="link_arm_l" />
    <axis
      xyz="0 -1 0" />
    <limit
      lower="0"
      upper="0"
      effort="6"
      velocity="0" />
  </joint>
  <link
    name="link_littlearm_l">
    <inertial>
      <origin
        xyz="0.128294239863031 0.0145 -4.16333634234434E-17"
        rpy="0 0 0" />
      <mass
        value="0.000157217277786466" />
      <inertia
        ixx="1.93415806521528E-05"
        ixy="1.08079552812825E-19"
        ixz="1.28112376477798E-19"
        iyy="0.000877613801366261"
        iyz="-8.09870755684815E-23"
        izz="0.000880308842483845" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_littlearm_l.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="1 1 1 1" />
      </material>
    </visual>
    <!-- <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="file://$(find urdf_simulate)/meshes/link_littlearm_l.STL" />
      </geometry>
    </collision> -->
  </link>
  <joint
    name="joint_littlearm_l"
    type="revolute">
    <origin
      xyz="-0.23682 0.02171 -0.03"
      rpy="0 0 0" />
    <parent
      link="link_arm_l" />
    <child
      link="link_littlearm_l" />
    <axis
      xyz="0 1 0" />
    <limit
      lower="0"
      upper="0"
      effort="6"
      velocity="0" />
  </joint>
  <link name="chassis">
    <!-- <visual>
            <geometry>
                <box size="${chassis_width} ${chassis_length} ${chassis_height}" />
            </geometry>
            <material name="gray" />
        </visual> -->
    <collision>
      <geometry>
        <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
      </geometry>
    </collision>
    <inertial>
      <mass value="0.001" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
    </inertial>
  </link>

  <!-- Joint for Body Top -->
  <xacro:property name="lift_origin"
    value="${-body_top_height / 2}" />
  <joint name="joint_chassis" type="prismatic">
    <parent link="base_link" />
    <child link="chassis" />
    <origin
      xyz="0 0 ${lift_origin}" />
    <axis xyz="0 0 -1" />
    <limit lower="${min_lift_height}" upper="${max_lift_height}"
      effort="1.0" velocity="1.0" />
  </joint>

  <!-- Joints for Wheels -->
  <joint name="joint_wheel_l" type="continuous">
    <parent link="chassis" />
    <child link="link_wheel_l" />
    <origin xyz="0 ${chassis_width/2} -${chassis_height/2}"
      rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <joint name="joint_wheel_r" type="continuous">
    <parent link="chassis" />
    <child link="link_wheel_r" />
    <origin xyz="0 ${-chassis_width/2} -${chassis_height/2}"
      rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <link name="caster_forward">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <geometry>
        <sphere radius="${caster_radius}" />
      </geometry>
    </collision>
    <!-- <inertial>
            <mass value="0.5" />
            <inertia ixx="3.000e-4" iyy="3.000e-4" izz="3.000e-4" ixy="0" ixz="0" iyz="0" />
        </inertial> -->
  </link>

  <link name="caster_backward">
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0" />
      <geometry>
        <sphere radius="${caster_radius}" />
      </geometry>
    </collision>
    <!-- <inertial>
            <mass value="0.5" />
            <inertia ixx="3.000e-4" iyy="3.000e-4" izz="3.000e-4" ixy="0" ixz="0" iyz="0" />
        </inertial> -->
  </link>

  <joint name="caster_forward_joint" type="fixed">
    <origin
      xyz="${body_top_length/2-caster_radius} 0 ${-chassis_height/2-wheel_radius+caster_radius+0.0001}"
      rpy="0 0 0" />
    <parent link="chassis" />
    <child link="caster_forward" />
  </joint>

  <joint name="caster_backward_joint" type="fixed">
    <origin
      xyz="${-body_top_length/2+caster_radius} 0 ${-chassis_height/2-wheel_radius+caster_radius+0.0001}"
      rpy="0 0 0" />
    <parent link="chassis" />
    <child link="caster_backward" />
  </joint>

  <!-- Transmission for the wheels -->
  <transmission name="trans_wheel_l">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_wheel_l">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="actuator_wheel_l">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="trans_wheel_r">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_wheel_r">
      <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
    </joint>
    <actuator name="actuator_wheel_r">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <!-- <transmission name="trans_chassis">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint_chassis">
      <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
    </joint>
    <actuator name="actuator_chassis">
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission> -->

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/$(arg ns)</robotNamespace>
    </plugin>
  </gazebo>
  <gazebo reference="caster_forward">
    <mu1 value="0.0" />
    <mu2 value="0.0" />
  </gazebo>
  <gazebo reference="caster_backward">
    <mu1 value="0.0" />
    <mu2 value="0.0" />
  </gazebo>
  <gazebo reference="link_wheel_l">
    <mu1 value="2.0" />
    <mu2 value="2.0" />
  </gazebo>
  <gazebo reference="link_wheel_r">
    <mu1 value="2.0" />
    <mu2 value="2.0" />
  </gazebo>

  <!-- <xacro:include filename="$(find urdf_simulate)/urdf/livox_mid360.xacro" />
  <xacro:Livox_Mid360 name="livox" />
  <joint name="joint_livox" type="fixed">
    <parent link="base_link" />
    <child link="livox_base" />
    <origin
      xyz="0 0 ${body_top_height}" />
    <axis xyz="0 0 1" />
  </joint> -->
</robot>