joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['joint_wheel_l']
  right_wheel: ['joint_wheel_r']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]
  wheel_separation: 0.42
  wheel_radius: 0.076
  cmd_vel_timeout: 0.25
  enable_odom_tf: false
  odom_frame_id: odom
  base_frame_id: base_link
  # publish_cmd: true
  # publish_cmd_topic: ~cmd_vel
  velocity_rolling_window_size: 10
  k_l: 0.5
  k_r: 0.5
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0  # m/s
      min_velocity           : -2.0 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1  # m/s^2
      min_acceleration       : -1 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.14  # rad/s
      # has_acceleration_limits: true
      # max_acceleration       : 20  # rad/s^2

# lift_controller:
#   type: position_controllers/JointPositionController
#   joint: joint_chassis
#   publish_rate: 50
#   pid: {p: 100.0, i: 1.0, d: 10.0,}
#   min_position: 0.1
#   max_position: 0.3

gazebo_ros_control:
  pid_gains:
    joint_wheel_l:
      p: 1.0
      i: 0.00
      d: 0
    joint_wheel_r:
      p: 1.0
      i: 0.00
      d: 0